FROM image-registry.openshift-image-registry.svc:5000/openshift/jenkins-agent-maven
#FROM registry.redhat.io/openshift4/ose-jenkins-agent-maven:v4.4

ENV CHROME_URL https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
ENV EPEL_URL https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
ENV PGDG_REPO_URL https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
USER root

# install dependenct packages for postgresql, selenium...
RUN dnf install -y ${EPEL_URL} ${PGDG_REPO_URL} ${CHROME_URL} \
    && dnf install -y postgresql chromedriver ipa-pgothic-fonts.noarch python-pip \
    && rm -rf /var/tmp/*
RUN pip install selenium
USER 1001
