apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
    - name: jnlp
      image: image-registry.openshift-image-registry.svc:5000/user1-operation/custom-jenkins-agent
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
      tty: false
      env:
        - name: JAVA_HOME
          #value: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64"
          value: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-2.el7_8.x86_64" # for v4.4
      resources:
        requests:
          cpu: 500m
          memory: 1024Mi
        limits:
          cpu: 500m
          memory: 1024Mi
    - name: postgres
      image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:10
      tty: false
      env:
        - name: POSTGRESQL_USER
          value: "freelancer"
        - name: POSTGRESQL_PASSWORD
          value: "password"
        - name: POSTGRESQL_DATABASE
          value: "freelancerdb_test"
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 100m
          memory: 256Mi
