# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: freelancerdb_test
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install postgresql client
      run: sudo apt-get update && sudo apt-get install -y postgresql
    - name: Set up test data
      run: PGPASSWORD=password psql -U postgres -d freelancerdb_test -h localhost -f etc/testdata.sql
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        PG_HOST: localhost
        PG_USER: postgres
        PG_PORT: 5432
        PG_PASSWORD: password

